const EDIT_BUTTON_CLICKED = 'EDIT_BUTTON_CLICKED';

const CANCEL_BUTTON_CLICKED = 'CANCEL_BUTTON_CLICKED';

const SAVE_BUTTON_CLICKED = 'SAVE_BUTTON_CLICKED';

const ADD_MEBMER = 'ADD_MEMBER';

const DELETE_MEBMER = 'DELETE_MEMBER';

const UPDATE_MEMBER = 'UPDATE_MEMBER';

export { EDIT_BUTTON_CLICKED, CANCEL_BUTTON_CLICKED, ADD_MEBMER, DELETE_MEBMER, UPDATE_MEMBER, SAVE_BUTTON_CLICKED }; // eslint-disable-line
